//
// Created by xiada on 2024/3/30.
//

#ifndef UNTITLED16_STATIC_VERIABLE_H
#define UNTITLED16_STATIC_VERIABLE_H

#define INCREMENT_ARRAY_SIZE_COEFFICIENT 5
#define DECREMENT_ARRAY_SIZE_COEFFICIENT 10
#define SCORE_MAIN_SUBJECT_MAX 100
#define SCORE_MAIN_SUBJECT_MIN 0
#define SCORE_PE_MAX 30
#define SCORE_PE_MIN 0
#define ONCE_SUBJECT_EXCELLENT 0.9
#define ONCE_SUBJECT_FINE 0.8
#define ONCE_SUBJECT_MIDDLE 0.7
#define ONCE_SUBJECT_PASS 0.6
#define END_ACTION 0
#define INCREMENT_MESSAGE_ACTION 1
#define DECREMENT_MESSAGE_ACTION 2
#define REPLACE_MESSAGE_ACTION 3
#define INCREMENT_SCORE_ACTION 4
#define DECREMENT_SCORE_ACTION 5
#define REPLACE_SCORE_ACTION 6
#define DOUBLE_SHIFT_ACTION 7
#define EXAMINE_ACTION 8
#define REPLACE_ID 1
#define REPLACE_NAME 2
#define REPLACE_CLASSNAME 3
#define REPLACE_UID 4
#define REPLACE_AGE 5
#define REPLACE_ADDRESS 6
#define REPLACE_EMAIL 7
#define DELETE_CHINESE 1
#define DELETE_MATH 2
#define DELETE_ENGLISH 3
#define DELETE_SPORT 4
#define DELETE_ALL_SUBJECT 5


#endif //UNTITLED16_STATIC_VERIABLE_H
